In [1]:
import pandas as pd
import time
import calendar

In [36]:
def weekdayColumn(df):
    '''
    Takes in pandas dataframe and creates 'weekday' column which represents
    the day of the week corresponding to Date.
    '''
    dates = [str(d).replace('/','') for d in list(df['Date'])]
    weekdays = [time.strptime(d,'%m%d%Y').tm_wday for d in dates]
    weekdays = [calendar.day_name[w] for w in weekdays]
    df['weekday'] = weekdays
    
def dateColumns(df):
    dates = [str(d).replace('/','') for d in list(df['Date'])]
    dates = [time.strptime(d,'%m%d%Y') for d in dates]
    df['MONTH'] = [d.tm_mon for d in dates]
    df['DAY'] = [d.tm_mday for d in dates]

def monthNameColumn(df):
    '''
    Takes in pandas dataframe and creates 'month' column.
    '''
    dates = [str(d).replace('/','') for d in list(flights_df['Date'])]
    dates = [time.strptime(d,'%m%d%Y').tm_mon for d in dates]
    df['month'] = [calendar.month_name[m] for m in dates]
    
def filterRoutes(df):
    '''
    filter df to contain delayed fligths from SFO to PHL routes only.
    '''
    df = df[(df['ORIGIN'] == 'SFO') & (df['DEST'] = 'PHL') & (df['ARR_DELAY'] > 0)]
    df = df.fillna(0, inplace=True)

In [106]:
df_list = [pd.read_csv('./month/jan2017.csv'), pd.read_csv('./month/feb2017.csv'), pd.read_csv('./month/mar2017.csv'),\
          pd.read_csv('./month/apr2017.csv'),pd.read_csv('./month/may2017.csv'), pd.read_csv('./month/jun2017.csv'),\
          pd.read_csv('./month/jul2017.csv'),pd.read_csv('./month/aug2017.csv'),pd.read_csv('./month/sep2017.csv'),\
          pd.read_csv('./month/oct2017.csv'),pd.read_csv('./month/nov2017.csv'),pd.read_csv('./month/dec2017.csv')]

In [107]:
feb_df = pd.read_csv('./month/feb2017.csv')
feb_df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,410507,410508,410509,410510,410511,410512,410513,410514,410515,410516
YEAR,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,...,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017
QUARTER,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
MONTH,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
DAY_OF_MONTH,25,26,27,28,1,2,3,4,5,6,...,15,16,17,18,19,20,21,22,23,24
DAY_OF_WEEK,6,7,1,2,3,4,5,6,7,1,...,3,4,5,6,7,1,2,3,4,5
UNIQUE_CARRIER,B6,B6,B6,B6,B6,B6,B6,B6,B6,B6,...,B6,B6,B6,B6,B6,B6,B6,B6,B6,B6
ORIGIN,MCO,MCO,MCO,MCO,BTV,BTV,BTV,BTV,BTV,BTV,...,MCO,MCO,MCO,MCO,MCO,MCO,MCO,MCO,MCO,MCO
DEST,EWR,EWR,EWR,EWR,JFK,JFK,JFK,JFK,JFK,JFK,...,EWR,EWR,EWR,EWR,EWR,EWR,EWR,EWR,EWR,EWR
CRS_DEP_TIME,1000,739,1028,739,1907,1907,1907,1907,1907,1907,...,624,739,1028,1000,739,1028,704,739,1028,1028
DEP_TIME,954,734,1039,729,1857,1854,1851,1843,1852,2054,...,614,NaN,1047,952,819,1039,659,733,1222,1036
DEP_DELAY,-6,-5,11,-10,-10,-13,-16,-24,-15,107,...,-10,NaN,19,-8,40,11,-5,-6,114,8
DEP_DELAY_NEW,0,0,11,0,0,0,0,0,0,107,...,0,NaN,19,0,40,11,0,0,114,8
DEP_DEL15,0,0,0,0,0,0,0,0,0,1,...,0,NaN,1,0,1,0,0,0,1,0
DEP_DELAY_GROUP,-1,-1,0,-1,-1,-1,-2,-2,-1,7,...,-1,NaN,1,-1,2,0,-1,-1,7,0
DEP_TIME_BLK,1000-1059,0700-0759,1000-1059,0700-0759,1900-1959,1900-1959,1900-1959,1900-1959,1900-1959,1900-1959,...,0600-0659,0700-0759,1000-1059,1000-1059,0700-0759,1000-1059,0700-0759,0700-0759,1000-1059,1000-1059
TAXI_OUT,10,15,11,34,16,13,17,14,15,34,...,11,NaN,16,13,20,21,12,18,24,19
WHEELS_OFF,1004,749,1050,803,1913,1907,1908,1857,1907,2128,...,625,NaN,1103,1005,839,1100,711,751,1246,1055
WHEELS_ON,1207,940,1255,1014,2019,2017,2009,1958,2005,2223,...,822,NaN,1316,1212,1052,1313,914,958,1453,1304
TAXI_IN,5,9,7,5,10,7,7,15,8,4,...,7,NaN,8,16,7,8,14,8,8,8
CRS_ARR_TIME,1236,1012,1306,1012,2037,2037,2037,2037,2037,2037,...,857,1012,1306,1236,1012,1306,937,1012,1306,1306
ARR_DELAY,-24,-23,-4,7,-8,-13,-21,-24,-24,110,...,-28,NaN,18,-8,47,15,-9,-6,115,6
ARR_DELAY_NEW,0,0,0,7,0,0,0,0,0,110,...,0,NaN,18,0,47,15,0,0,115,6
ARR_DEL15,0,0,0,0,0,0,0,0,0,1,...,0,NaN,1,0,1,1,0,0,1,0
DIVERTED,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CARRIER_DELAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,0,NaN,40,11,NaN,NaN,10,NaN
WEATHER_DELAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,0,NaN,0,0,NaN,NaN,0,NaN
NAS_DELAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,NaN,NaN,7,NaN,7,4,NaN,NaN,1,NaN
SECURITY_DELAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,0,NaN,0,0,NaN,NaN,0,NaN
LATE_AIRCRAFT_DELAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107,...,NaN,NaN,11,NaN,0,0,NaN,NaN,104,NaN
Unnamed: 29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Read in Airport information from ASPM (SFO-PHL pair city data and individual airport data files) and merge into flights_df.

In [62]:
# read in SFO to PHL flight delay information
dot_df = pd.read_csv('flights.csv').dropna(axis=0,how='all')
# keep departure, arrival hour info, drop minutes
dot_df['SCHEDULED_DEPARTURE'] = [t // 100 for t in list(dot_df['SCHEDULED_DEPARTURE'])]
dot_df['SCHEDULED_ARRIVAL'] = [t // 100 for t in list(dot_df['SCHEDULED_ARRIVAL'])]
# remove ARRIVAL_DELAY = 0, CANCELLED != 0
dot_df = dot_df[(dot_df['ORIGIN_AIRPORT']=='SFO') & (dot_df['DESTINATION_AIRPORT']=='PHL') & (dot_df['ARRIVAL_DELAY'] != 0.0) & (dot_df['CANCELLED'] == 0)].reset_index()
dot_df = dot_df.drop(['index','YEAR','FLIGHT_NUMBER','ORIGIN_AIRPORT','DESTINATION_AIRPORT','DEPARTURE_TIME','ARRIVAL_TIME','TAIL_NUMBER','CANCELLED','CANCELLATION_REASON'],axis=1)
dot_df.fillna(0,inplace=True)

In [63]:
dot_df.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,...,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_DELAY,DIVERTED,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,1,1,4,US,8,1.0,12.0,838.0,317.0,312.0,...,1634.0,4.0,16,-4.0,0,0.0,0.0,0.0,0.0,0.0
1,1,1,4,UA,11,18.0,21.0,1209.0,323.0,313.0,...,1957.0,4.0,19,8.0,0,0.0,0.0,0.0,0.0,0.0
2,1,1,4,US,13,9.0,17.0,1406.0,310.0,314.0,...,2200.0,3.0,21,13.0,0,0.0,0.0,0.0,0.0,0.0
3,1,1,4,US,22,-9.0,13.0,2204.0,307.0,302.0,...,543.0,10.0,6,-14.0,0,0.0,0.0,0.0,0.0,0.0
4,1,1,4,UA,22,-4.0,14.0,2240.0,319.0,304.0,...,620.0,10.0,6,-19.0,0,0.0,0.0,0.0,0.0,0.0

In [92]:
# read in detailed airport information

airports_df = pd.read_csv('airport_delay.csv').dropna(axis=0,how='all')
# split Date into MONTH and DAY
airports_df['Facility'] = airports_df['Facility'].str.strip()
dateColumns(airports_df)
airports_df = airports_df.drop(['% DelayedGateDepartures','% DelayedGateArrivals','Date'],axis=1)
airports_df = airports_df.drop(['DeparturesFor MetricComputation','ArrivalsFor MetricComputation','DelayedGateDepartures','DelayedGateArrivals','AverageMinutesOf DelayPer DelayedGateDeparture','AverageMinutesOf DelayPer DelayedGateArrival'],axis=1)

# measure of congestion
airports_df['netOutfluxPHL'] = airports_df['ScheduledDepartures'] - airports_df['ScheduledArrivals']
airports_df['netInfluxSFO'] = airports_df['ScheduledArrivals'] - airports_df['ScheduledDepartures']
airports_df = airports_df.rename(columns={'ScheduledDepartures':'ScheduledDeparturesCount',\
                                         'ScheduledArrivals':'ScheduledArrivalsCount'})

In [90]:
airports_df.head()

,Facility,Hour,ScheduledDeparturesCount,ScheduledArrivalsCount,MONTH,DAY,netOutfluxPHL,netInfluxSFO
0,PHL,0,0,3,1,1,-3,3
1,PHL,1,0,2,1,1,-2,2
2,PHL,5,2,1,1,1,1,-1
3,PHL,6,8,7,1,1,1,-1
4,PHL,7,6,2,1,1,4,-4

In [93]:
airports_phl_df = airports_df[airports_df['Facility']=='PHL']
airports_sfo_df = airports_df[airports_df['Facility']=='SFO']

In [96]:
airports_phl_df.head()

,Facility,Hour,ScheduledDeparturesCount,ScheduledArrivalsCount,MONTH,DAY,netOutfluxPHL,netInfluxSFO
0,PHL,0,0,3,1,1,-3,3
1,PHL,1,0,2,1,1,-2,2
2,PHL,5,2,1,1,1,1,-1
3,PHL,6,8,7,1,1,1,-1
4,PHL,7,6,2,1,1,4,-4

In [98]:
dot_df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,340,341,342,343,344,345,346,347,348,349
MONTH,1,1,1,1,1,1,1,1,1,1,...,3,3,3,3,3,3,3,3,3,3
DAY,1,1,1,1,1,2,2,2,2,2,...,8,8,8,8,9,9,9,9,9,10
DAY_OF_WEEK,4,4,4,4,4,5,5,5,5,5,...,7,7,7,7,1,1,1,1,1,2
AIRLINE,US,UA,US,US,UA,US,US,US,UA,US,...,UA,US,US,UA,US,US,UA,US,UA,US
SCHEDULED_DEPARTURE,8,11,13,22,22,6,8,11,11,13,...,10,10,22,22,8,10,10,22,22,8
DEPARTURE_DELAY,1,18,9,-9,-4,-4,-3,-5,1,-3,...,-1,-4,-10,47,-4,33,55,-13,13,-1
TAXI_OUT,12,21,17,13,14,17,15,17,31,13,...,23,17,12,18,17,12,10,17,27,19
WHEELS_OFF,838,1209,1406,2204,2240,628,837,1112,1202,1350,...,1117,1108,2202,2342,838,1140,1200,2204,2315,843
SCHEDULED_TIME,317,323,310,307,319,315,317,318,323,310,...,323,314,306,319,317,314,323,306,319,317
ELAPSED_TIME,312,313,314,302,304,306,308,308,320,297,...,303,295,297,303,311,299,306,304,325,326
AIR_TIME,296,288,294,279,280,286,284,286,286,276,...,277,275,276,277,288,283,292,284,289,296
DISTANCE,2521,2521,2521,2521,2521,2521,2521,2521,2521,2521,...,2521,2521,2521,2521,2521,2521,2521,2521,2521,2521
WHEELS_ON,1634,1957,2200,543,620,1414,1621,1858,1948,2126,...,1854,1843,538,719,1626,1923,1952,548,704,1639
TAXI_IN,4,4,3,10,10,3,9,5,3,8,...,3,3,9,8,6,4,4,3,9,11
SCHEDULED_ARRIVAL,16,19,21,6,6,14,16,19,19,21,...,19,19,6,6,16,19,19,6,6,16
ARRIVAL_DELAY,-4,8,13,-14,-19,-13,-12,-15,-2,-16,...,-21,-23,-19,31,-10,18,38,-15,19,8
DIVERTED,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AIR_SYSTEM_DELAY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,0
SECURITY_DELAY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AIRLINE_DELAY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,31,0,7,7,0,7,0
LATE_AIRCRAFT_DELAY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,11,31,0,6,0
WEATHER_DELAY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [86]:
flights_df = pd.merge(dot_df, airports_df, how='inner', left_on=['MONTH','DAY','SCHEDULED_DEPARTURE'],\
               right_on=['MONTH','DAY','Hour'])
flights_df = flights_df.drop(['Hour','Hour'],axis=1)
temp.shape

(350, 28)

In [87]:
temp.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,...,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,Facility,Hour,ScheduledDepartures,ScheduledArrivals,netOutfluxPHL,netInfluxSFO
0,1,1,4,US,8,1.0,12.0,838.0,317.0,312.0,...,0.0,0.0,0.0,0.0,PHL,8,6,2,4,-4
1,1,1,4,UA,11,18.0,21.0,1209.0,323.0,313.0,...,0.0,0.0,0.0,0.0,PHL,11,13,6,7,-7
2,1,1,4,US,13,9.0,17.0,1406.0,310.0,314.0,...,0.0,0.0,0.0,0.0,PHL,13,45,28,17,-17
3,1,1,4,US,22,-9.0,13.0,2204.0,307.0,302.0,...,0.0,0.0,0.0,0.0,PHL,22,10,18,-8,8
4,1,1,4,UA,22,-4.0,14.0,2240.0,319.0,304.0,...,0.0,0.0,0.0,0.0,PHL,22,10,18,-8,8

In [88]:
list(temp)

['MONTH',
 'DAY',
 'DAY_OF_WEEK',
 'AIRLINE',
 'SCHEDULED_DEPARTURE',
 'DEPARTURE_DELAY',
 'TAXI_OUT',
 'WHEELS_OFF',
 'SCHEDULED_TIME',
 'ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'WHEELS_ON',
 'TAXI_IN',
 'SCHEDULED_ARRIVAL',
 'ARRIVAL_DELAY',
 'DIVERTED',
 'AIR_SYSTEM_DELAY',
 'SECURITY_DELAY',
 'AIRLINE_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'WEATHER_DELAY',
 'Facility',
 'Hour',
 'ScheduledDepartures',
 'ScheduledArrivals',
 'netOutfluxPHL',
 'netInfluxSFO']

In [ ]:
# merge airport info with flight info for PHL
airports_phl_df = pd.merge(flights_df, airports_phl_df,  \
                   how='inner', left_on=['Arrival','Date','ArrivalHour'], \
                   right_on = ['Facility','Date','Hour'])
airports_phl_df = airports_phl_df.drop(['Hour','Facility'],axis=1)

# merge airport info with flight info for SFO
airports_sfo_df = pd.merge(flights_df, airports_sfo_df,  \
                   how='inner', left_on=['Departure','Date','DepartureHour'], \
                   right_on = ['Facility','Date','Hour'])
airports_sfo_df = airports_sfo_df.drop(['Hour','Facility'],axis=1)

# add airport schedule info to flights_df
flights_df['ScheduledDeparturesSFO'] = airports_sfo_df['ScheduledDepartures']
flights_df['ScheduledArrivalsSFO'] = airports_sfo_df['ScheduledArrivals']
flights_df['ScheduledDeparturesPHL'] = airports_phl_df['ScheduledDepartures']
flights_df['ScheduledArrivalsPHL'] = airports_phl_df['ScheduledArrivals']

# remove Departure (SFO) and Arrival (PHL) columns
flights_df = flights_df.drop(['Departure','Arrival'],axis=1)

# add weekday and month names
weekdayColumn(flights_df)
monthColumn(flights_df)